#------------------------------------------------------------------------
# 기본 설정 (JAR 실행 시 사용)
#------------------------------------------------------------------------
server:
  port: 8080
  servlet:
    context-path: /smuxapi

spring:
  web:
    resources:
      static-locations: classpath:/static/
      add-mappings: true

logging:
  config: classpath:log4j2.xml

#------------------------------------------------------------------------
# WAR 프로파일 설정 (WAR 배포 시 자동 적용)
# WAR 배포 시 context-path를 /로 설정
#------------------------------------------------------------------------
---
spring:
  config:
    activate:
      on-profile: war

server:
  servlet:
    context-path: /
